src/Store/Controllers/GoodPageController.cs
using DAL.Classes.UnitOfWork;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Store.Controllers
{
    public class GoodPageController : Controller
    {
        private readonly UnitOfWork unitOfWork;

        public GoodPageController(AppDbContext appDbContext)
        {
            this.unitOfWork = new UnitOfWork(appDbContext);
        }

        public async Task<IActionResult> ShowGood(int goodId)
        {
            Good good = await unitOfWork.Goods.Get(goodId);
            good.Producer = await unitOfWork.Producers.Get(good.ProducerId);

            return View(good);
        }

        [Authorize(Roles = "customer")]
        [HttpPost]
        public async Task<IActionResult> LeaveReview(int id, string reviewArea)
        {
            Customer customer = unitOfWork.Customers.GetAll().Where(c => c.Email == User.Identity.Name).First();

            if (customer != null)
            {
                GoodReview review = new GoodReview
                {
                    Customer = customer,
                    Date = DateTime.Now,
                    Message = reviewArea,
                    StarCount = 0
                };

                Good good = await unitOfWork.Goods.Get(id);

                await unitOfWork.Goods.AddReview(review, good);
                await unitOfWork.SaveAsync();
            }

            return View();
        }

        [Authorize(Roles = "customer")]
        [HttpPost]
        public async Task<IActionResult> AddToCart(int id)
        {
            Good good = await unitOfWork.Goods.Get(id);
            int customerId = unitOfWork.Customers.GetAll().Where(c => c.Email == User.Identity.Name).First().Id;
            Customer customer = await unitOfWork.Customers.Get(customerId);

            if (good != null && customer != null)
            {
                unitOfWork.Customers.AddToCart(good, customer);
                await unitOfWork.SaveAsync();
            }
            return RedirectToAction("ShowGood", new { goodid = id });
        }

        [Authorize(Roles = "customer")]
        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int goodid)
        {
            Good good = await unitOfWork.Goods.Get(goodid);
            int customerId = unitOfWork.Customers.GetAll().Where(c => c.Email == User.Identity.Name).First().Id;
            Customer customer = await unitOfWork.Customers.Get(customerId);

            if (good != null && customer != null)
            {
                unitOfWork.Customers.RemoveFromCart(good, customer);
                await unitOfWork.SaveAsync();
            }
            return RedirectToAction("ShowCart", "Account");
        }
    }
}

src/Store/Views/GoodPage/ShowGood.cshtml
@model DAL.Models.Good
@{
    ViewData["Title"] = Model.Name;
}
<link rel="stylesheet" href="~/css/mainPage.css" />
<div class="container content">
    <div class="row product-page">
        <div class="col-lg-6 image">
            <img src="../images/goods/@Model.PhotoUrl" />
        </div>
        <div class="col-lg-6">
            <h2>@Model.Name</h2>
            <p>
                @Model.Specification
            </p>
            @if (Model.YearOfManufacture != 0)
            {
                <p>
                    Year : @Model.YearOfManufacture
                </p>
            }
            @if (Model.WarrantyTerm != 0)
            {
                <p>
                    Warranty term (months) : @Model.WarrantyTerm
                </p>
            }
            @if (Model.Type != null)
            {
                <p>
                    Type : @Model.Type
                </p>
            }
            @if (Model.Producer != null)
            {
                <p>
                    Producer : @Model.Producer.Name
                </p>
            }
            <p>
                Color:
            </p>
            <ul class="circles">
                <li>
                    <div class="white-circle"></div>
                </li>
                <li>
                    <div class="red-circle"></div>
                </li>
                <li>
                    <div class="black-circle"></div>
                </li>
            </ul>
            <hr class="black-hr" />
            <form asp-action="AddToCart" asp-controller="GoodPage" asp-route-id="@Model.Id">
                <div class="price">
                    <p>
                        @Model.Price
                    </p>
                    <button class="btn btn-green">Add to cart</button>
                </div>
            </form>
        </div>
    </div>
    <hr class="black-hr" />
    <form asp-action="LeaveReview" asp-controller="GoodPage" asp-route-id="@Model.Id">
        <div class="row product-review text-center">
            <p class="visible-lg-inline">Rate product </p>
            <div class="row">
                <div class="col-lg-3 col-lg-offset-4 text-center">
                    <ul class="rate">
                        <li class="star"></li>
                        <li class="star"></li>
                        <li class="star"></li>
                        <li class="star"></li>
                        <li class="star"></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6 col-lg-offset-3 form-group">
                <textarea class="form-control" id="FormControlTextarea1" rows="8" name="reviewArea"></textarea>
            </div>
        </div>
        <div class="row text-center">
            <button class="btn btn-primary">Live a review</button>
        </div>
    </form>
    <hr class="black-hr" />
    <div class="row text-center">
        <a href="#">Show rewiews</a>
    </div>
</div>